export const LANGUAGE_OPTIONS = [
    { label: "Tiếng Việt", value: "Tiếng Việt" },
    { label: "Tiếng Anh", value: "Tiếng Anh" },
    { label: "Tiếng Trung", value: "Tiếng Trung" },
    { label: "Tiếng Nhật", value: "Tiếng Nhật" },
    { label: "Tiếng Hàn", value: "Tiếng Hàn" },
    { label: "Tiếng Pháp", value: "Tiếng Pháp" },
    { label: "Tiếng Đức", value: "Tiếng Đức" },
    { label: "Tiếng Tây Ban Nha", value: "Tiếng Tây Ban Nha" },
    { label: "Tiếng Bồ Đào Nha", value: "Tiếng Bồ Đào Nha" },
    { label: "Tiếng Ý", value: "Tiếng Ý" },
    { label: "Tiếng Nga", value: "Tiếng Nga" },
    { label: "Tiếng Thái", value: "Tiếng Thái" },
    { label: "Tiếng Ả Rập", value: "Tiếng Ả Rập" },
    { label: "Tiếng Hindi", value: "Tiếng Hindi" },
    { label: "Tiếng Indonesia", value: "Tiếng Indonesia" },
    { label: "Tiếng Malaysia", value: "Tiếng Malaysia" },
    { label: "Tiếng Philippines", value: "Tiếng Philippines" },
    { label: "Tiếng Thổ Nhĩ Kỳ", value: "Tiếng Thổ Nhĩ Kỳ" },
    { label: "Tiếng Hà Lan", value: "Tiếng Hà Lan" },
    { label: "Tiếng Na Uy", value: "Tiếng Na Uy" },
    { label: "Tiếng Thụy Điển", value: "Tiếng Thụy Điển" },
    { label: "Tiếng Đan Mạch", value: "Tiếng Đan Mạch" },
    { label: "Tiếng Ba Lan", value: "Tiếng Ba Lan" },
    { label: "Tiếng Séc", value: "Tiếng Séc" },
    { label: "Tiếng Hy Lạp", value: "Tiếng Hy Lạp" },
    { label: "Tiếng Hungary", value: "Tiếng Hungary" },
    { label: "Tiếng Romania", value: "Tiếng Romania" },
    { label: "Tiếng Ukraina", value: "Tiếng Ukraina" },
    { label: "Tiếng Phần Lan", value: "Tiếng Phần Lan" },
  ];
  
  export const COUNTRY_OPTIONS = [
    { label: "Việt Nam", value: "Việt Nam" },
    { label: "Mỹ", value: "Mỹ" },
    { label: "Anh", value: "Anh" },
    { label: "Pháp", value: "Pháp" },
    { label: "Đức", value: "Đức" },
    { label: "Nhật Bản", value: "Nhật Bản" },
    { label: "Hàn Quốc", value: "Hàn Quốc" },
    { label: "Trung Quốc", value: "Trung Quốc" },
    { label: "Ấn Độ", value: "Ấn Độ" },
    { label: "Canada", value: "Canada" },
    { label: "Úc", value: "Úc" },
    { label: "Tây Ban Nha", value: "Tây Ban Nha" },
    { label: "Ý", value: "Ý" },
    { label: "Brazil", value: "Brazil" },
    { label: "Mexico", value: "Mexico" },
    { label: "Nga", value: "Nga" },
    { label: "Thái Lan", value: "Thái Lan" },
    { label: "Indonesia", value: "Indonesia" },
    { label: "Philippines", value: "Philippines" },
    { label: "Malaysia", value: "Malaysia" },
    { label: "Singapore", value: "Singapore" },
    { label: "Thụy Sĩ", value: "Thụy Sĩ" },
    { label: "Hà Lan", value: "Hà Lan" },
    { label: "Thụy Điển", value: "Thụy Điển" },
    { label: "Na Uy", value: "Na Uy" },
    { label: "Đan Mạch", value: "Đan Mạch" },
    { label: "Phần Lan", value: "Phần Lan" },
    { label: "Ba Lan", value: "Ba Lan" },
    { label: "Argentina", value: "Argentina" },
    { label: "Chile", value: "Chile" },
    { label: "New Zealand", value: "New Zealand" },
    { label: "Ukraina", value: "Ukraina" },
    { label: "Thổ Nhĩ Kỳ", value: "Thổ Nhĩ Kỳ" },
    { label: "Ả Rập Xê Út", value: "Ả Rập Xê Út" },
    {
      label: "Các Tiểu Vương Quốc Ả Rập Thống Nhất",
      value: "Các Tiểu Vương Quốc Ả Rập Thống Nhất",
    },
    { label: "Ai Cập", value: "Ai Cập" },
    { label: "Nam Phi", value: "Nam Phi" },
    { label: "Iran", value: "Iran" },
    { label: "Pakistan", value: "Pakistan" },
    { label: "Bangladesh", value: "Bangladesh" },
    { label: "Bồ Đào Nha", value: "Bồ Đào Nha" },
    { label: "Hy Lạp", value: "Hy Lạp" },
    { label: "Ireland", value: "Ireland" },
    { label: "Czech", value: "Czech" },
    { label: "Hungary", value: "Hungary" },
    { label: "Romania", value: "Romania" },
    { label: "Israel", value: "Israel" },
    { label: "Colombia", value: "Colombia" },
    { label: "Peru", value: "Peru" },
  ];